"""empty message

Revision ID: b55dc260b97a
Revises: 113c563d3f44
Create Date: 2020-03-14 14:12:02.913879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55dc260b97a'
down_revision = '113c563d3f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('created_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'created_on')
    # ### end Alembic commands ###
