"""empty message

Revision ID: fa437de67ac1
Revises: 4c46575fa409
Create Date: 2020-03-12 16:11:58.293299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa437de67ac1'
down_revision = '4c46575fa409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile_pic_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'profile_pic_id')
    # ### end Alembic commands ###
